package com.qttx.kedouhulian.bean

data class TaskBean(
        val  order_id:String = "",
        var score: String= "",
        var aid:String = "",
        var task_id: String = "",
        var from_uid: String = "",
        var restrict_times: Int = 0,
        var area_id: Int = 0,
        var area_name: String = "",
        var area_num: Int = 0,
        var avatar: String = "",
        var cid: Int = 0,
        var content: String = "",
        var create_time: Long = 0,
        var create_time_text: String = "",
        var finish_num: Int = 0,
        var heat: Int = 0,
        var id:String = "",
        var imgs: String = "",
        var imgs_list: List<String> = listOf(),
        var is_top: Int = 0,
        var limit_area: Int = 0,
        var limit_reply: Int = 0,
        var limit_sex: Int = 0,
        var nickname: String = "",
        var paymoney: String = "",
        var service_price: String = "",
        var service_rate: String = "",
        var show_img: Int = 0,
        var status: Int = 0,
        var task_price: String = "",
        var task_time: Int = 0,
        var title: String = "",
        var top_price: String = "",
        var total_num: Int = 0,
        var type_name: String = "",
        var uid: String = "",
        var area: String? = null,
        var dsnum: Int = 0,
        var rate: Double = 0.0,
        var amend_status: Int = 0,
        var limit_time: Long = 0


)